services:
  - type: web
    name: retinal-age-app
    env: docker
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: GIT_LFS_SKIP_SMUDGE
        value: "0"
