services:
  - type: web
    name: retinal-age-app
    env: docker
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /
    autoDeploy: true
    buildFilter:
      paths:
        - webapp/**
        - Dockerfile
        - render.yaml
